# Numpy intro notebook
python numpy library examples and exercises

In [1]:
# import numpy
import numpy as np

In [2]:
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
ap = [1,2,3]

In [5]:
ap

[1, 2, 3]

In [6]:
type(a1)

numpy.ndarray

In [7]:
type(ap)

list

In [8]:
a2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [9]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]
    ]
])

In [11]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

### Attribute describe the shape of array

In [12]:
a1.shape

(3,)

In [13]:
# 2 for y 3 for x (y, x)
a2.shape

(2, 3)

In [14]:
# (z, y, x) len of array inside a3
a3.shape

(2, 3, 3)

In [15]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [16]:
type(a1.shape)

tuple

# number of dimentional

In [17]:
a1.ndim

1

In [18]:
a2.ndim

2

In [19]:
a3.ndim

3

In [20]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [21]:
type(a1.ndim)

int

In [22]:
type((a1.ndim, a2.ndim, a3.ndim))

tuple

In [23]:
mix_type = np.array(['this is a string', 1, 0.5])

In [24]:
type(mix_type[0]), type(mix_type[1]), type(mix_type[2])

(numpy.str_, numpy.str_, numpy.str_)

In [25]:
# automaticaly convert every element to string when there is a string in array
mix_type

array(['this is a string', '1', '0.5'], dtype='<U16')

In [26]:
mix_type.dtype

dtype('<U16')

### numpy convert int to float when mix int with float

In [27]:
float_int = np.array([1, 2.3, 4])

In [28]:
float_int

array([1. , 2.3, 4. ])

In [29]:
float_int.dtype

dtype('float64')

### Check how many element in array

In [30]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [31]:
len(a1)

3

In [32]:
# only count the length of the outside array
len(a2)

2

In [33]:
len(a3)

2

In [34]:
len(a3[1])

3

In [35]:
uneven = np.array([
    [11, 22, 32],
    [44, 55]
])

In [36]:
# numpy array contain python list because of unequal amount of element in each list
uneven

array([list([11, 22, 32]), list([44, 55])], dtype=object)

In [37]:
uneven.shape

(2,)

In [38]:
# count as one dimention
uneven.ndim

1

In [39]:
twonp_in = np.array([np.array([1, 2, 3]), np.array([4, 5])])

In [40]:
twonp_in

array([array([1, 2, 3]), array([4, 5])], dtype=object)

In [41]:
twonp_in.ndim

1

In [42]:
one_element_2d = np.array([[1],[2]])

In [43]:
one_element_2d

array([[1],
       [2]])

## Note
-Numpy need same number of elements inside an array for a multiple dimentional shape array.

-If there are different type of data in an array, Numpy will try and automatically convert all of the element to the same type.

-If the type of the element in array are not numerical type, Numpy will show the dtype.

## Numpy with Pandas

In [44]:
#import pandas
import pandas as pd

In [45]:
num_data = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))
num_data

0  1  2
0  1  2  3
1  4  5  6

## Creating arrays

In [46]:
# basic creating an array
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [47]:
random_int = np.random.randint(10, size=(3, 3))
random_int

array([[1, 5, 1],
       [3, 6, 4],
       [8, 3, 5]])

In [48]:
random_random = np.random.random((2, 3))
random_random

array([[0.88392065, 0.57171503, 0.05370085],
       [0.9646943 , 0.39808752, 0.09396129]])

In [49]:
random_rand = np.random.rand(5, 3)
random_rand

array([[0.06671823, 0.92285485, 0.99742569],
       [0.574509  , 0.56805813, 0.89585049],
       [0.34097744, 0.2287845 , 0.01218065],
       [0.78504445, 0.99280279, 0.55307448],
       [0.96921714, 0.48044902, 0.87819862]])

In [50]:
array_range = np.arange(0, 10, 1)
array_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
ones = np.ones((2, 3, 2, 2), dtype=np.int8)
ones

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]], dtype=int8)

In [52]:
ones.ndim

4

In [53]:
zeros = np.zeros(5, dtype=np.int8)
zeros

array([0, 0, 0, 0, 0], dtype=int8)

In [54]:
type(zeros)

numpy.ndarray

In [55]:
np.random.seed(24)
np.random.randint(5, 20, size=(2, 5))

array([[ 7,  8,  5, 12,  6],
       [ 6,  6,  9, 16,  9]])

In [56]:
np.random.seed(457)
np.random.rand(2, 4, 5)

array([[[0.18190703, 0.32305927, 0.13262878, 0.54852835, 0.73721259],
        [0.10155765, 0.72817591, 0.08835447, 0.9619707 , 0.00944708],
        [0.04556102, 0.66154552, 0.84134824, 0.75992134, 0.09419566],
        [0.94996042, 0.79175395, 0.00544731, 0.53199545, 0.05792312]],

       [[0.30425753, 0.8055233 , 0.16508507, 0.80963408, 0.61759987],
        [0.62172138, 0.08884106, 0.61200465, 0.2952694 , 0.99309036],
        [0.73783392, 0.51748632, 0.56672152, 0.14805446, 0.01807557],
        [0.69374931, 0.49384959, 0.38111295, 0.40024415, 0.38939535]]])

In [57]:
# find all unique in array
np.unique(random_int)

array([1, 3, 4, 5, 6, 8])

In [58]:
random_int

array([[1, 5, 1],
       [3, 6, 4],
       [8, 3, 5]])

In [59]:
np.where(random_int == 8)

(array([2], dtype=int64), array([0], dtype=int64))

In [60]:
np.where(random_int == 3)

(array([1, 2], dtype=int64), array([0, 1], dtype=int64))

In [61]:
random_int[0][2]

1

In [62]:
random_int[2][0]

8

In [63]:
# slice syntax to view a silce of array
# an order alway start from most outer array (y, x)
random_int[:2, :3]

array([[1, 5, 1],
       [3, 6, 4]])

In [64]:
# combination of slice and indexing
# chose row number 2 with 3 element of colunm
# random_int[2] slice 3
random_int[2, :3]

array([8, 3, 5])

In [65]:
# same as above
random_int[2][:3]

array([8, 3, 5])

In [66]:
# this get slice of first 2 row and get the column number 2 of each
# ->[[4, 4, (8)],
# -> [0, 6, (5)],
#    [3, 8,  9 ]]
random_int[:2, 2]

array([1, 4])

In [67]:
p_list = [1, 2, 3]

In [68]:
np.sum(p_list)

6

In [69]:
sum(p_list)

6

In [70]:
%timeit sum(p_list)
%timeit np.sum(p_list)

227 ns ± 57.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
16.5 µs ± 8.92 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [71]:
%timeit sum(a1)
%timeit np.sum(a1)

1.95 µs ± 186 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
5.39 µs ± 596 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [72]:
massive = np.ones(10000, dtype=np.int8)

In [73]:
massive[:5]

array([1, 1, 1, 1, 1], dtype=int8)

In [74]:
%timeit sum(massive)
%timeit np.sum(massive)

3.07 ms ± 405 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
18.3 µs ± 2.31 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [75]:
massive_list = []
for x in range(10000):
    massive_list.append(1)

In [76]:
massive_list[:5]

[1, 1, 1, 1, 1]

In [77]:
%timeit sum(massive_list)
%timeit np.sum(massive_list)

94.2 µs ± 3.25 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
734 µs ± 17.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [78]:
len(massive)

10000

In [79]:
len(massive_list)

10000

## Numpy Math operations

In [80]:
a1 + a1

array([2, 4, 6])

In [81]:
a2 + a1

array([[2, 4, 6],
       [5, 7, 9]])

In [82]:
a3 + a1

array([[[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]],

       [[ 1,  3,  5],
        [ 4,  6,  8],
        [ 7,  9, 11]]])

## Numpy aggregation function
example of numpy aggregation (np.sum)

In [84]:
# create an array with all 1 int8 type
all_ones = np.ones((100, 100))

In [86]:
all_ones[:10, :10]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])