# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [70]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [71]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[0, 9, 8], [7, 6, 5], [4, 3, 2]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [72]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
(a1.shape, a1.ndim, a1.dtype, a1.size, type(a1))

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [73]:
# Attributes of 2-dimensional array
(a2.shape, a2.ndim, a1.dtype, a1.size, type(a2))

((2, 3), 2, dtype('int32'), 3, numpy.ndarray)

In [74]:
# Attributes of 3-dimensional array
(a3.shape, a3.ndim, a3.dtype, a3.size, type(a3))

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [75]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
pd.DataFrame(a2)

0  1  2
0  1  2  3
1  4  5  6

In [76]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2), dtype=np.int8)
ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [77]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3), dtype=np.int8)
zeros

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int8)

In [78]:
# Create an array within a range of 0 and 100 with step 3
arange = np.arange(0, 100, 3)
arange

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [79]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
randrange = np.random.randint(0, 10, size=(7,2))
randrange

array([[8, 8],
       [0, 8],
       [6, 8],
       [7, 0],
       [7, 7],
       [2, 0],
       [7, 2]])

In [80]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randfloat = np.random.rand(3, 5)
randfloat

array([[0.79017554, 0.60595997, 0.92630088, 0.65107703, 0.91495968],
       [0.85003858, 0.44945067, 0.09541012, 0.37081825, 0.66884125],
       [0.66592236, 0.59129779, 0.27472179, 0.56124343, 0.38292687]])

In [81]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
randseed = np.random.randint(0, 10, size=(4, 6))
randseed

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [82]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
randa = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(randa)

array([1, 2, 3, 4, 5, 7, 9])

In [83]:
# Find the 0'th index of the latest array you created
randa[0]

array([9, 1, 3, 7, 4, 9, 3])

In [84]:
# Get the first 2 rows of latest array you created
randa[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [85]:
# Get the first 2 rows of latest array you created
randa[:, :2]

array([[9, 1],
       [5, 3],
       [4, 9]])

In [86]:
# Get the first 2 values of the first 2 rows of the latest array
randa[:2, :2]

array([[9, 1],
       [5, 3]])

In [87]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ss1 = np.random.randint(0, 10, size=(3, 5), dtype=np.int8)
ss2 = np.ones((3, 5), dtype=np.int8)
(ss1, ss2)

(array([[8, 3, 5, 0, 6],
        [5, 8, 9, 3, 7],
        [3, 5, 8, 2, 0]], dtype=int8),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=int8))

In [88]:
# Add the two arrays together
ss1 + ss2

array([[ 9,  4,  6,  1,  7],
       [ 6,  9, 10,  4,  8],
       [ 4,  6,  9,  3,  1]], dtype=int8)

In [89]:
# Create another array of ones of shape (5, 3)
ss3 = np.ones((5,3), dtype=np.int8)
ss3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [90]:
# Try add the array of ones and the other most recent array together
ss2 + ss3.T

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]], dtype=int8)

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [91]:
# Create another array of ones of shape (3, 5)
ss4 = np.ones((3, 5), dtype=np.int8)
ss4

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [92]:
# Subtract the new array of ones from the other most recent array
ss4 - ss2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [93]:
# Multiply the ones array with the latest array
ss1 * ss4

array([[8, 3, 5, 0, 6],
       [5, 8, 9, 3, 7],
       [3, 5, 8, 2, 0]], dtype=int8)

In [94]:
# Take the latest array to the power of 2 using '**'
ss1 ** 2

array([[64,  9, 25,  0, 36],
       [25, 64, 81,  9, 49],
       [ 9, 25, 64,  4,  0]], dtype=int8)

In [95]:
# Do the same thing with np.square()
np.square(ss1)

array([[64,  9, 25,  0, 36],
       [25, 64, 81,  9, 49],
       [ 9, 25, 64,  4,  0]], dtype=int8)

In [96]:
# Find the mean of the latest array using np.mean()
np.mean(ss1)

4.8

In [97]:
# Find the maximum of the latest array using np.max()
np.max(ss1)

9

In [98]:
# Find the minimum of the latest array using np.min()
np.min(ss1)

0

In [99]:
# Find the standard deviation of the latest array
np.std(ss1)

2.809507667427397

In [100]:
# Find the variance of the latest array
np.var(ss1)

7.8933333333333335

In [101]:
# Reshape the latest array to (3, 5, 1)
ss1.reshape((3, 5, 1))

array([[[8],
        [3],
        [5],
        [0],
        [6]],

       [[5],
        [8],
        [9],
        [3],
        [7]],

       [[3],
        [5],
        [8],
        [2],
        [0]]], dtype=int8)

In [102]:
# Transpose the latest array
ss1.T

array([[8, 5, 3],
       [3, 8, 5],
       [5, 9, 8],
       [0, 3, 2],
       [6, 7, 0]], dtype=int8)

What does the transpose do?

In [103]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
aa1 = np.random.randint(0, 10, size=(3, 3), dtype=np.int8)
aa2 = np.random.randint(0, 10, size=(3, 2), dtype=np.int8)

In [104]:
# Perform a dot product on the two newest arrays you created
np.dot(aa1, aa2)

array([[ 91, 105],
       [ 15,  13],
       [ 56,  68]], dtype=int8)

In [105]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rint1 = np.random.randint(0, 10, size=(4,3 ), dtype=np.int16)
rint2 = np.random.randint(0, 10, size=(4, 3), dtype=np.int16)

In [106]:
# Perform a dot product on the two newest arrays you created
rint1.dot(rint2.T)

array([[ 59,  82,  69,  96],
       [ 99,  96,  69, 128],
       [ 53,  73,  45,  81],
       [ 55,  74,  39,  81]], dtype=int16)

It doesn't work. How would you fix it?

In [107]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(rint1.T, rint2)

array([[116, 136, 141],
       [105, 111, 130],
       [ 68,  55,  54]], dtype=int16)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [108]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
randint1 = np.random.randint(0, 10, size=(2, 2))
randint2 = np.random.randint(0, 10, size=(2, 2))

In [109]:
# Compare the two arrays with '>'
randint1 > randint2

array([[ True,  True],
       [False, False]])

What happens when you compare the arrays with `>`?

In [110]:
# Compare the two arrays with '>='
randint1 >= randint2

array([[ True,  True],
       [ True, False]])

In [111]:
# Find which elements of the first array are greater than 7
randint1 > 7

array([[False,  True],
       [False, False]])

In [112]:
# Which parts of each array are equal? (try using '==')
randint1 == randint2

array([[False, False],
       [ True, False]])

In [113]:
# Sort one of the arrays you just created in ascending order
np.sort(randint1, axis=1)

array([[6, 8],
       [4, 7]])

In [122]:
# Sort the indexes of one of the arrays you just created
np.argsort(randint1, axis=0)

array([[0, 1],
       [1, 0]], dtype=int64)

In [128]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(randint1)

1

In [127]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(randint1)

3

In [126]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(randint1, axis=1)

array([1, 0], dtype=int64)

In [132]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(randint1, axis=0)

array([0, 1], dtype=int64)

In [131]:
# Create an array of normally distributed random numbers
np.random.random(20)

array([0.60703425, 0.27599918, 0.29627351, 0.16526694, 0.01563641,
       0.42340148, 0.39488152, 0.29348817, 0.01407982, 0.1988424 ,
       0.71134195, 0.79017554, 0.60595997, 0.92630088, 0.65107703,
       0.91495968, 0.85003858, 0.44945067, 0.09541012, 0.37081825])

In [129]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.